### ISSUE TITLE
hbs and node-jsx do not get along well?

### ISSUE THREAD

**Issue by arian-hosseinzadeh** [donpark/hbs#106]
I'm using react to create components of my Nodejs app.

To compile react components , I need to `require("node-jx").install()` in my router file and render it using hbs. But it gives me the following error :

    Error: Error transforming node_modules/hbs/lib/hbs.js to JS: Error: Parse Error: Line 34: Unexpected token ;

This happens when I load the page (not during the build).

    var JSX = require('node-jsx').install(),//as we don't reactify it while building
    React = require('react'),
    Game = React.createFactory(require('../components/game')),
    Board = React.createFactory(require('../components/board')),
    DataStore = require('../store/store');

    var router = require('express').Router();

    router.get('/', function(req, res) {
    var initialState = {'users': DataStore.getUsers()};
    var markup = React.renderToString(
        Board(initialState)
    );
    res.render('board', {
        markup: markup,
        state: JSON.stringify(initialState),
        layout: 'boardLayout'
    });
    });

    router.get('/:opponent', function(req, res) {
    var opponent = req.params.opponent;
    if (DataStore.isPlaying(opponent)){
        res.render('error', {
            message: opponent + ' is already busy playing !',
            error:{
                status: '',
                stack: ''
            }
        });
    }else{
        var initialState = {'users': ''}; // inspect this one , do we need to do this at all ?
        var markup = React.renderToString(
            Game(initialState)
        );
        res.render('game', {
            markup: markup,
            state: JSON.stringify(initialState),
            layout: 'gameLayout'
        });
    }
    });

    module.exports = router;

**Comment by defunctzombie** [comment]
Probably because hbs cannot understand jsx syntax on the page and thinks the syntax is invalid. Maybe something else is causing the error. Better to ask on stack overflow since there are many modules at play here. If you can make a simple example without all the extra jsx modules and some syntax issue that can be looked at but otherwise there is too much going on.

You should also provide information about what you did to debug the problem when you post issues since your code above is useless to anyone who doesn't have your full codebase.
