### ISSUE TITLE
Update to handlebars 4.0.0

### ISSUE THREAD

**Issue by Friend-LGA** [donpark/hbs#107]
And in package.json may be better use 
```"handlebars": "^4.0.0"```
not
```"handlebars": "4.0.0"```

**Comment by defunctzombie** [comment]
No, `^` is not better. It means the code that backs this module changes with every new install. This loads to subtle breakage and non-deterministic installs.

That issue aside; I would entertain a PR for the update with passing tests and some notes about what changed in handlebars v4 so that we can help users migrate with any breaking changes.

**Comment by Friend-LGA** [comment]
Ok. I found that we can use custom version of handlebars with function ```create``` and handlebars 4.0.2 working fine. I will  waiting for your official update, good luck!
