### ISSUE TITLE
Upgrade version of handlebars

### ISSUE THREAD

**Issue by michaelBenin** [donpark/hbs#85]
https://www.npmjs.com/package/handlebars - 3.0.0

**Comment by cappslock** [comment]
Why does this need to be a package dependency at all? It seems like it makes more sense to remove it and allow the consuming party to provide their own Handlebars instance, either explicitly through a factory method or by simply including it in their package.json so that a `require('handlebars')` call works.

**Comment by defunctzombie** [comment]
Because some people just want to install `hbs` and have view rendering work. In their mind `hbs` is the view engine.

The other reason is handlebars can break API and I don't want to get issue reports about someone trying to use a version of handlebars that I haven't tested against.

Happy to look at a PR for upgrading to handlebars 3.0.0. Tests should pass tho :)
