### ISSUE TITLE
Use semver for handlebars in package.json

### ISSUE THREAD

**Issue by dpolivy** [donpark/hbs#99]
I see this package was recently updated to use `handlebars@3.0.0` -- but in order to continue picking up bugfixes, shouldn't it be versioned as `^3.0.0` in [package.json](https://github.com/donpark/hbs/blob/master/package.json#L12)?

https://docs.npmjs.com/misc/semver#caret-ranges-1-2-3-0-2-5-0-0-4

**Comment by defunctzombie** [comment]
no. I dislike this approach because handlebars can introduce subtle changes even for minor versions that will break code. Safest is to use a specific version and upgrade as needed. Caret ranges are bad for module use over the longer term.

If you want to use a newer handlebars we can do a PR (if there is a specific feature or fix) or you can specify your own version for hbs to use iirc.
